[package]
name = "srg"
version = "20251214.0.0"
edition = "2021"
authors = ["Jake Goldsborough"]
license = "MIT"

[dependencies]
jobl = { git = "https://github.com/ducks/jobl" }
clap = { version = "4.5", features = ["derive"] }
anyhow = "1.0"
headless_chrome = "1.0"
