[package]
name = "srg"
version = "0.1.0"
edition = "2021"
authors = ["Jake Goldsborough"]
license = "MIT"

[dependencies]
jobl = { path = "../jobl" }
clap = { version = "4.5", features = ["derive"] }
anyhow = "1.0"
